#!/usr/bin/env python 

import shlex, subprocess, time

time.sleep(5)

with open('/nucypher/alice_key.txt', 'r') as myfile:
        data=myfile.read().replace('\n', '')        

command="nucypher enrico run --policy-encrypting-key " + data
args = shlex.split(command)
print(args)

subprocess.run(args)

