#!/usr/bin/env python

import shlex, subprocess, time
import os.path
import datetime

file_path = "/nucypher/alice_policy_pubkey"
while not os.path.exists(file_path):
    time.sleep(1)

if os.path.isfile(file_path):
    with open(file_path, 'r') as myfile:
        data=myfile.read().replace('\n', '')
    command="nucypher enrico run --policy-encrypting-key " + data
    args = shlex.split(command)
    print(args)
    subprocess.run(args)
else:
    raise ValueError("%s isn't a file!" % file_path)


